### ISSUE TITLE
Script text in slider

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Shannon#4]
Please add script font text to the slider image just as it is in the attached image. Here's are the text lines to be added below:

"I'm looking for fellow 
patriots who want to help 
me promote conservative policy, 
uphold the Constitution, 
and defend our traditional values. 
I hope you'll join me."

T.W. Shannon

[twconcept-v2.pdf](https://github.com/VeritasStrategies/Shannon/files/112996/twconcept-v2.pdf)

**Comment by santosh-ricom** [comment]
Done chages
