### ISSUE TITLE
Center menu bar

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Shannon#5]
Please center the menu bar links on the page, except for the "Sign up" button. Leave the "Sign up" button on the right and give it a navy background color, just as in the attached example.
![tw3](https://cloud.githubusercontent.com/assets/13319038/12731087/a54e3a32-c8f4-11e5-85a5-c88e36f1ae51.jpg)

**Comment by santosh-ricom** [comment]
Done chages once check
